app:
  kafka:
    topic:
      name: json-message-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: error
    org.springframework.web: error
    com.melardev: debug
